from chota import app, db
from flask import render_template, redirect, request, flash, jsonify
from chota.models import Url
from urlparse import urlparse
import string
import random
import re
import httplib2


def _protocol(url):
    """
    Checks if http:// is present before Url
    """
    parsed = urlparse(url)
    if parsed.scheme == "":
        return "http://" + url
    else:
        return url


def _check_netloc(url):
    """
    Checks if the url is already shortened
    """
    shortened_list = ["bit.ly", "goo.gl", "owl.ly", "deck.ly", "su.pr"]
    parsed = urlparse(url)
    if parsed.netloc in shortened_list:
        return True
    else:
        return False


def _is_valid_url(url):
    """
    Validates the URL input
    """
    regex = re.compile(
        r'^(?:http|ftp)s?://'  # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?'
        r'|[A-Z0-9-]{2,}\.?)|'  # domain...
        r'localhost|'  # localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|'  # ...or ipv4
        r'\[?[A-F0-9]*:[A-F0-9:]+\]?)'  # ...or ipv6
        r'(?::\d+)?'  # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)
    if regex.search(url):
        return True
    return False


def _url_exists(url):
    """
    Get the headers of a web resource to check if it exists
    """
    h = httplib2.Http()
    try:
        resp = h.request(url, 'HEAD')
        if resp[0].status == 200:
            return True
    except (httplib2.RelativeURIError, httplib2.ServerNotFoundError):
        return False


def _random_string():
    """
    Generates a random code for adding to short url
    """
    length = 6
    rv = ""
    for i in range(length):
        rv += random.choice(string.ascii_lowercase)
    return rv


def _shorten_url(url):
    """
    Functions returns short url
    """
    url = _protocol(url.strip())
    if _url_exists(url):
        long_url = Url.query.filter_by(url=url).first()
        # Checks if someone has already shortened the same url
        if long_url is None:
            inserted = False
            random_code = _random_string()
            # Checks if the the same random was generated by the function
            while not inserted:
                check_code = Url.query.filter_by(random_code=random_code). \
                    first()
                if check_code is None:
                    short_url = Url(random_code, url)
                    db.session.add(short_url)
                    db.session.commit()
                    inserted = True
                else:
                    random_code = _random_string()
            return "http://chota-tk.herokuapp.com/" + random_code
        else:
            # If the url is present in the db, it returns the already created
            # short url
            return "http://chota-tk.herokuapp.com/" + long_url.random_code
    else:
        return False


def _expand_url(code):
    """
    Returns expanded url
    """
    long_url = Url.query.filter_by(random_code=code).first()
    # Checks if the short url is valid
    if long_url is None:
        return False
    else:
        return long_url.url


@app.route('/', methods=["GET"])
def main():
    """
    Returns the main page upon GET request
    """
    return render_template('index.html')


@app.route('/form', methods=["POST"])
def form():
    url = request.form['url']
    u = _protocol(url)
    if u == "http://chota-tk.herokuapp.com/":
        flash("Can't shorten my own url")
        return render_template("index.html")
    if _check_netloc(u):
        flash("The Url is already short")
        return render_template("index.html")
    else:
        short_url = _shorten_url(url)
        if not short_url:
            flash("Invalid url, try again")
            return render_template("index.html")
        else:
            return render_template('shortened.html', url=short_url)


@app.errorhandler(404)
def handle_error():
    """
    404 error handler function
    """
    return render_template("404.html"), 404


@app.route('/api/<long_url>', methods=["GET"])
def api(long_url=None):
    """
    Api request handler function
    """
    url = long_url
    short_url = _shorten_url(url)
    if not short_url:
        return jsonify(success=False, message="Invalid url")
    else:
        return jsonify(success=True, short_url=short_url)


@app.route('/<string:handler>', methods=["GET"])
def handle_url(handler=None):
    """
    Function to redirect short url's to original url
    """
    long_url = _expand_url(handler)
    if not long_url:
        # Returns to the main page if the url is not presented in the database
        return redirect('/', code=302)
    else:
        return redirect(long_url, code=302)
